from pathlib import Path

root = Path('.')

repo_contract = '''from pathlib import Path\nroot = Path(__file__).resolve().parents[1]\napp = (root / 'hub/app.py').read_text()\nrepo = (root / 'hub/monitor_incident_repository.py').read_text()\nmonitoring = (root / 'hub/monitoring_router.py').read_text()\nincidents = (root / 'hub/incidents_router.py').read_text()\nassert "with_name('monitor_incident_repository.py')" in app\nassert '_monitor_incident_repository_spec.loader.exec_module' in app\nfor marker in ['def fetch_monitor_inventory(', 'def fetch_monitor_result_rows(', 'def fetch_incident_inventory(', 'def fetch_incident_detail_rows(']:\n    assert marker in repo\nassert 'fetch_monitor_inventory(db)' in monitoring\nassert 'fetch_monitor_result_rows(db, monitor_id, limit)' in monitoring\nassert 'fetch_incident_inventory(db)' in incidents\nassert 'fetch_incident_detail_rows(db, incident_id)' in incidents\nfor marker in [\n    'SELECT monitors.*,nodes.name node_name,nodes.role node_role,nodes.host node_host',\n    'SELECT ts,status,latency_ms,detail FROM monitor_results WHERE monitor_id=?',\n    '(SELECT COUNT(*) FROM incident_events WHERE incident_id=incidents.id) event_count',\n    'SELECT incident_events.*,users.username actor',\n]:\n    assert marker in repo\n    assert marker not in app\nfor mutation_marker, owner in [\n    ('@router.post("/api/monitors", status_code=201)', monitoring),\n    ('@router.put("/api/monitors/{monitor_id}")', monitoring),\n    ('@router.post("/api/incidents/{incident_id}/notes", status_code=201)', incidents),\n    ('@router.post("/api/incidents/{incident_id}/action")', incidents),\n]:\n    assert mutation_marker in owner\nassert 'VERSION = "2.9.29"' in app\nprint('Monitor/Incident repository query boundary passed')\n'''
(root / 'tests/backend_monitor_incident_repository_contract.py').write_text(repo_contract)

service_contract = '''from pathlib import Path\n\nroot = Path(__file__).resolve().parents[1]\napp = (root / "hub/app.py").read_text()\nservice = (root / "hub/monitor_incident_service.py").read_text()\nmonitoring = (root / "hub/monitoring_router.py").read_text()\nincidents = (root / "hub/incidents_router.py").read_text()\n\nassert "with_name('monitor_incident_service.py')" in app\nassert "_monitor_incident_service_spec.loader.exec_module" in app\nfor marker in [\n    "class MonitorIncidentServiceError",\n    "def create_monitor_mutation(",\n    "def update_monitor_mutation(",\n    "def delete_monitor_mutation(",\n    "def queue_monitor_run_mutation(",\n    "def add_incident_note_mutation(",\n    "def incident_action_mutation(",\n]:\n    assert marker in service\n\nfor call, owner in [\n    ("create_monitor_mutation(", monitoring),\n    ("update_monitor_mutation(", monitoring),\n    ("delete_monitor_mutation(", monitoring),\n    ("queue_monitor_run_mutation(", monitoring),\n    ("add_incident_note_mutation(", incidents),\n    ("incident_action_mutation(", incidents),\n]:\n    assert call in owner\n\nfor route, owner in [\n    ('@router.post("/api/monitors", status_code=201)', monitoring),\n    ('@router.put("/api/monitors/{monitor_id}")', monitoring),\n    ('@router.delete("/api/monitors/{monitor_id}")', monitoring),\n    ('@router.post("/api/monitors/{monitor_id}/run", status_code=202)', monitoring),\n    ('@router.post("/api/incidents/{incident_id}/notes", status_code=201)', incidents),\n    ('@router.post("/api/incidents/{incident_id}/action")', incidents),\n]:\n    assert route in owner\n\nfor marker in [\n    "INSERT INTO monitors(node_id,name,kind,target,port,secret_enc",\n    "UPDATE monitors SET node_id=?,name=?,kind=?,target=?",\n    "DELETE FROM monitors WHERE id=?",\n    "UPDATE incidents SET status='acknowledged'",\n    "UPDATE incidents SET status='open',resolved_at=NULL",\n]:\n    assert marker in service\n    assert marker not in app\n\nassert 'VERSION = "2.9.29"' in app\nprint("Monitor/Incident mutation service boundary passed")\n'''
(root / 'tests/backend_monitor_incident_service_contract.py').write_text(service_contract)
